version: "3.9"
services:
  jenkens-docker:
    image: docker:dind
    privileged: true
    environment: 
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
    ports:
      - "2376:2376"
    networks:
      - jenkens
    command: --storage-driver=overlay2

  jenkins-blueocean:
    build: .
    environment: 
      - DOCKER_HOST=tcp://jenkens-docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - jenkens
    depends_on:
      - jenkens-docker
  
volumes:
  jenkins-data: {}
  jenkins-docker-certs: {}

networks:
  jenkens: {}
